<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vehicle Notification</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 0;
            padding: 20px;
            background-color: #f4f4f4;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            background-color: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        .header {
            background-color: #2563eb;
            color: white;
            padding: 20px;
            text-align: center;
            border-radius: 8px 8px 0 0;
            margin: -30px -30px 30px -30px;
        }
        .vehicle-list {
            margin: 20px 0;
        }
        .vehicle-item {
            background-color: #f8f9fa;
            border: 1px solid #e9ecef;
            border-radius: 5px;
            padding: 15px;
            margin-bottom: 10px;
        }
        .plate-number {
            font-weight: bold;
            color: #2563eb;
            font-size: 18px;
        }
        .vehicle-details {
            margin-top: 8px;
            color: #666;
        }
        .summary {
            background-color: #e7f3ff;
            border-left: 4px solid #2563eb;
            padding: 15px;
            margin: 20px 0;
        }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #e9ecef;
            color: #666;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Monthly Vehicle Notification</h1>
            <p>Vehicles with Plate Numbers Ending in {{ $lastDigit }}</p>
        </div>

        <div class="summary">
            <h3>Notification Summary</h3>
            <p><strong>Date:</strong> {{ $notificationDate }}</p>
            <p><strong>Last Digit Filter:</strong> {{ $lastDigit }}</p>
            <p><strong>Total Vehicles:</strong> {{ $vehicles->count() }}</p>
        </div>

        @if($vehicles->count() > 0)
            <div class="vehicle-list">
                <h3>Vehicle Details</h3>
                @foreach($vehicles as $vehicle)
                    <div class="vehicle-item">
                        <div class="plate-number">{{ $vehicle->plate_number }}</div>
                        <div class="vehicle-details">
                            <strong>Type:</strong> {{ $vehicle->vehicle_type ?? 'Not specified' }}<br>
                            <strong>Brand:</strong> {{ $vehicle->vehicle_brand ?? 'Not specified' }}<br>
                            <strong>Owner:</strong> {{ $vehicle->vehicle_owner ?? 'Not specified' }}<br>
                            <strong>Company:</strong> {{ $vehicle->company_name ?? 'Not specified' }}<br>
                            <strong>Status:</strong> {{ $vehicle->vehicle_status ?? 'Not specified' }}<br>
                            <strong>Date Added:</strong> {{ $vehicle->add_date_in_company ? $vehicle->add_date_in_company->format('Y-m-d') : 'Not specified' }}
                        </div>
                    </div>
                @endforeach
            </div>
        @else
            <div class="vehicle-list">
                <p style="text-align: center; color: #666; font-style: italic;">
                    No vehicles found with plate numbers ending in {{ $lastDigit }}.
                </p>
            </div>
        @endif

        <div class="footer">
            <p>This is an automated notification sent on {{ $notificationDate }}.</p>
            <p>This notification is sent 5 days before the 1st of each month for vehicles based on their plate number's last digit.</p>
            <p><strong>Note:</strong> This email was automatically generated by the Vehicle Management System.</p>
        </div>
    </div>
</body>
</html>